.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. YinchengCoin_qt test_YinchengCoin_qt
clean: FORCE
	$(MAKE) -C .. YinchengCoin_qt_clean test_YinchengCoin_qt_clean
check: FORCE
	$(MAKE) -C .. test_YinchengCoin_qt_check
YinchengCoin-qt YinchengCoin-qt.exe: FORCE
	 $(MAKE) -C .. YinchengCoin_qt
